tubeletter/chakra-ui-clone

- .idea/.gitignore
- .idea/chakra-ui-clone.iml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/modules.xml
- .idea/vcs.xml
- packages/chakra-ui-styled/src/test/Test.stories.tsx
> 🎉 new branch : styled

- README.md
- packages/chakra-ui-styled/src/foundation/typography/Heading.stories.tsx
- packages/chakra-ui-styled/src/foundation/typography/Heading.tsx
- packages/chakra-ui-styled/src/foundation/typography/Text.tsx
- packages/chakra-ui-styled/src/foundation/typography/Texts.stories.tsx
- packages/chakra-ui-styled/src/foundation/typography/typography.types.ts
> add typography stories

- packages/chakra-ui-styled/src/foundation/colors/color.ts
- packages/chakra-ui-styled/src/foundation/radii/Radii.stories.tsx
- packages/chakra-ui-styled/src/foundation/radii/radii.ts
- packages/chakra-ui-styled/src/foundation/radii/radii.types.ts
- 기본 컬러 컴포넌트에 누적시켜 사용할 'gray200' 추가
- radius 옵션에 number만 들어갈 수 있도록 설정 후, rem단위의 배율값이 확정되면 import 가능하게끔 구성해 봄
> branch resetting and radii push

- apps/team-styled/.storybook/preview.ts
- packages/chakra-ui-styled/src/foundation/breakpoints/Breakpoints.stories.tsx
- packages/chakra-ui-styled/src/foundation/breakpoints/breakpoint.ts
- packages/chakra-ui-styled/src/foundation/breakpoints/breakpoint.types.ts
feat : breakpoints add.
- breakpoint 파일 생성
- storybook viewport 설정추가
> feat : breakpoints add.

- apps/team-styled/.storybook/preview.ts
- packages/chakra-ui-styled/src/foundation/breakpoints/Breakpoints.stories.tsx
- packages/chakra-ui-styled/src/foundation/breakpoints/breakpoint.ts
fix : breakpoints 설정 변경.
- breakpoint viewport 크기 오작성 부분 수정 (preview / bp size )
- storybook viewport 설명 테이블 추가
- 
> fix : breakpoint docs add

- packages/chakra-ui-sass/src/foundation/colors/color.module.scss
- packages/chakra-ui-sass/src/foundation/colors/color.stories.tsx
- packages/chakra-ui-sass/src/foundation/colors/color.tsx
- packages/chakra-ui-sass/src/style/theme.scss
Color 컴포넌트 및 스타일작업
*공통 스타일 폴더 및 변수파일 추가
*Color 폴더 및 파일 추가
> SCSS Color Component and Style

- .idea/prettier.xml
- packages/chakra-ui-styled/src/foundation/typography/Heading.stories.tsx
- packages/chakra-ui-styled/src/foundation/typography/Heading.styled.ts
- packages/chakra-ui-styled/src/foundation/typography/Heading.tsx
- packages/chakra-ui-styled/src/foundation/typography/Text.styled.ts
- packages/chakra-ui-styled/src/foundation/typography/Text.tsx
- packages/chakra-ui-styled/src/foundation/typography/Texts.stories.tsx
- packages/chakra-ui-styled/src/foundation/typography/typography.ts
- packages/chakra-ui-styled/src/foundation/typography/typography.types.ts
> 타이포그라피 수정사항입니다.

- packages/chakra-ui-styled/src/foundation/containers/Containers.stories.tsx
- packages/chakra-ui-styled/src/foundation/containers/container.ts
- packages/chakra-ui-styled/src/foundation/containers/container.types.ts
- packages/chakra-ui-styled/src/foundation/radii/Radii.stories.tsx
- packages/chakra-ui-styled/src/foundation/shadows/Shadows.stories.tsx
- packages/chakra-ui-styled/src/foundation/shadows/shadow.ts
- packages/chakra-ui-styled/src/foundation/shadows/shadows.types.ts
containers 추가 및 shadows, radii 수정
- containers 파일 생성
- shadows, radii css 오타수정 
- 각 컴포넌트 index.ts 삭제
- shadows가 merge 안 된 상태에서 추가 fix하여 버스태웠습니다.
> containers add & shadows, radii fix

- packages/chakra-ui-styled/src/foundation/breakpoints/Breakpoints.stories.tsx
- packages/chakra-ui-styled/src/foundation/breakpoints/breakpoint.ts
- packages/chakra-ui-styled/src/foundation/radii/radii.types.ts
- packages/chakra-ui-styled/src/foundation/spacings/Spacings.stories.tsx
- packages/chakra-ui-styled/src/styles/ChakraThemeProvider.tsx
- feat : theme bps, raddi, spacing, shadow add
- themeprovider 추가 ( breakpoint, raddi, spacing, shadow)
> feat : theme bps, raddi, spacing, shadow add

- packages/chakra-ui-styled/src/foundation/colors/Colors.stories.tsx
- packages/chakra-ui-styled/src/foundation/colors/Colors.tsx
- packages/chakra-ui-styled/src/foundation/colors/color.types.ts
- packages/chakra-ui-styled/src/foundation/colors/colorPalette.ts
- packages/chakra-ui-styled/src/foundation/typography/typography.ts
- packages/chakra-ui-styled/src/foundation/typography/typography.types.ts
- packages/chakra-ui-styled/src/styles/ChakraThemeProvider.tsx
feat : themeprovider color,typo,container add.
- color, typo, container add
> feat : themeprovider color,typo,container add.

- packages/chakra-ui-styled/src/foundation/typography/Text.styled.ts
- packages/chakra-ui-styled/src/foundation/typography/Text.tsx
> fix : typo fixed

- packages/chakra-ui-styled/src/components/button/Button.stories.tsx
- packages/chakra-ui-styled/src/components/button/Button.tsx
feat : 버튼 설정
- 버튼 색상 추가
- 버튼 스토리 추가
- 스토리 컨트롤 추가
- 버튼 아이콘 추후 변경 해야함
- 버튼 텍스트 컴포넌트 업데이트 시 변경수정해야함
- hover, focus 관련 가이드가 없음
> feat : button add.

- packages/chakra-ui-styled/src/foundation/typography/Heading.stories.tsx
- packages/chakra-ui-styled/src/foundation/typography/Heading.styled.ts
- packages/chakra-ui-styled/src/foundation/typography/Heading.tsx
- packages/chakra-ui-styled/src/foundation/typography/Text.styled.ts
- packages/chakra-ui-styled/src/foundation/typography/Text.tsx
- packages/chakra-ui-styled/src/foundation/typography/Texts.stories.tsx
fix : typo setting
- 타이포 스타일 파일 분리
- 타이포 children text 표기 변경
- 헤딩/텍스트 웨잍 리팩토링
- 헤딩 굵기 추가
> fix : typo setting

- packages/chakra-ui-styled/src/components/form/button/Button.stories.tsx
- packages/chakra-ui-styled/src/components/form/button/Button.styled.tsx
- packages/chakra-ui-styled/src/components/form/button/Button.tsx
fix : refactor btn
- 버튼 리팩토링 (스타일, 버튼 파일분리)
- 스토리북 변경
- 버튼 타입 변경
- 아이콘 더미로 직접 삽입할수있게 변경
- 텍스트 스타일 적용
> fix : refactor btn

- packages/chakra-ui-styled/src/components/badge/Badge.stories.tsx
- packages/chakra-ui-styled/src/components/badge/Badge.styled.tsx
- packages/chakra-ui-styled/src/components/badge/Badge.tsx
fix : badge add
- 배지 제작
- 스토리북 배열. 테스트로 사용
> feature : badge add

- packages/chakra-ui-styled/src/components/tabs/Tabs.stories.tsx
- packages/chakra-ui-styled/src/components/tabs/Tabs.tsx
- packages/chakra-ui-styled/src/components/tabs/tab/Tab.tsx
- packages/chakra-ui-styled/src/components/tabs/tab/tab.types.ts
- style 예약어로 오류 styleType로 명칭변경
- spacings 오타로 spacing 으로 변경
- styles 명칭 명확하게 tabStyle로 변경 
- 타입 ==> 인터페이스로 변경
> fix : tab fix

- packages/chakra-ui-styled/src/components/form/checkbox/Checbok.stories.tsx
- packages/chakra-ui-styled/src/components/form/checkbox/Checkbox.tsx
- packages/chakra-ui-styled/src/components/form/radio/Radio.stories.tsx
- packages/chakra-ui-styled/src/components/form/radio/Radio.tsx
라디오버튼 제작 및 잉여코드 제거
- 라디오버튼 제작완료
- 체크박스 내 불필요 주석 및 잉여코드 제거 
- #34 feature/components-styled에 merge하고 origin/feature/components-styled-checkbox-final-runa 삭제시도.
- 이후 feature/components-styled-radio-runa 제작되었습니다.
> 라디오버튼 제작 및 잉여코드 제거

- packages/chakra-ui-sass/src/components/card/Card.module.scss
- packages/chakra-ui-sass/src/components/card/Card.stories.tsx
- packages/chakra-ui-sass/src/components/card/Card.tsx
- packages/chakra-ui-sass/src/components/card/Card.types.ts
- packages/chakra-ui-sass/src/components/card/body/CardBody.module.scss
- packages/chakra-ui-sass/src/components/card/body/CardBody.tsx
- packages/chakra-ui-sass/src/components/card/body/CardBody.types.ts
- packages/chakra-ui-sass/src/components/card/footer/CardFooter.tsx
- packages/chakra-ui-sass/src/components/card/footer/CardHeader.types.ts
- packages/chakra-ui-sass/src/components/card/header/CardHeader.tsx
- packages/chakra-ui-sass/src/components/card/header/CardHeader.types.ts
- packages/chakra-ui-sass/src/components/card/index.ts
- packages/chakra-ui-sass/src/foundation/root/_root.scss
- packages/chakra-ui-sass/src/foundation/root/_shadows-root.scss
- packages/chakra-ui-sass/src/foundation/variables/_radius-variables.scss
- packages/chakra-ui-sass/src/foundation/variables/_shadows-variables.scss
- packages/chakra-ui-sass/src/types/props.types.ts
- packages/chakra-ui-sass/src/types/size.types.ts
개인적으로 Compound Pattern을 좋아하는데 카드에는 아직 해당 패턴을 적용시킬만한 기능이 현재 없는데...
추후에 나온다면 Context API가 들어가야할 수도 있음
> feat(sass): card 컴포넌트 추가

- packages/chakra-ui-styled/src/components/form/closebutton/CloseButton.stories.tsx
- packages/chakra-ui-styled/src/components/form/closebutton/CloseButton.tsx
- packages/chakra-ui-styled/src/components/form/closebutton/CloseButtonstyled.tsx
- packages/chakra-ui-styled/src/components/form/textarea/Textarea.stories.tsx
- packages/chakra-ui-styled/src/components/form/textarea/Textarea.tsx
Fix/components styled textarea andclose fix bboing
- form제어시 disabled,readonly로 스타일 제어 해야합니당
- textarea 조건부분은 스타일 참고해주세요. 
- 아이콘 사이즈 변경했습니다~ height가 누락~ svg는width, height줘야해용~~
> fix : close btn and textarea fix

- .idea/jsLinters/eslint.xml
- .idea/material_theme_project_new.xml
- apps/team-styled/package.json
- packages/chakra-ui-styled/src/components/tabs/Tabs.stories.tsx
- packages/chakra-ui-styled/src/components/tabs/Tabs.tsx
- packages/chakra-ui-styled/src/components/tabs/tab/Tab.stories.tsx
- packages/chakra-ui-styled/src/components/tabs/tab/Tab.tsx
- packages/chakra-ui-styled/src/components/tabs/tab/tab.types.ts
- packages/chakra-ui-styled/src/foundation/typography/Text.styled.ts
- packages/chakra-ui-styled/src/foundation/typography/typography.types.ts
- pnpm-lock.yaml
스토리북 정상작동됩니다.
단 구조상 active boolean은 작업구조를 약간바꿔야할거같아서 후순위로 미루었습니다.
* tab은 3개인데 active true 할시 어떤걸 active할지 고민안해봄.
> 컴포넌트 / 탭스 작업 완료했습니다. 

- packages/chakra-ui-styled/src/foundation/typography/Heading.stories.tsx
- packages/chakra-ui-styled/src/foundation/typography/Heading.tsx
- packages/chakra-ui-styled/src/foundation/typography/Text.tsx
- packages/chakra-ui-styled/src/foundation/typography/Texts.stories.tsx
- packages/chakra-ui-styled/src/foundation/typography/typography.ts
> fix : typo error, remove stories

- packages/chakra-ui-styled/src/styles/ChakraThemeProvider.tsx
> fix : typo lineheight
